# Generated by Django 4.0.4 on 2022-10-18 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_filemodel_filefiled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='status',
            new_name='lable_status',
        ),
    ]
