# Generated by Django 4.0.4 on 2022-11-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='status',
            new_name='statusmodel',
        ),
    ]
